name: CI/CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Dar permisos de ejecución a mvnw
        run: chmod +x ./mvnw

      - name: Compilar el proyecto con Maven
        run: ./mvnw clean package -DskipTests

      - name: Copiar los jars compilados a la EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "eureka/target/*.jar,api-gateway/target/*.jar,ms-usuarios/target/*.jar,ms-catalogo/target/*.jar,ms-recursos/target/*.jar"
          target: "/home/ubuntu/app-deploy"
          strip_components: 0

      - name: Actualizar jars y reiniciar servicios systemd
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cp /home/ubuntu/app-deploy/eureka/target/*.jar       /home/ubuntu/micros/eureka.jar
            cp /home/ubuntu/app-deploy/ms-usuarios/target/*.jar   /home/ubuntu/micros/ms-usuarios.jar
            cp /home/ubuntu/app-deploy/ms-catalogo/target/*.jar   /home/ubuntu/micros/ms-catalogo.jar
            cp /home/ubuntu/app-deploy/ms-recursos/target/*.jar   /home/ubuntu/micros/ms-recursos.jar
            cp /home/ubuntu/app-deploy/api-gateway/target/*.jar   /home/ubuntu/micros/api-gateway.jar

            sudo systemctl restart eureka.service
            sleep 20
            sudo systemctl restart ms-usuarios.service
            sleep 15
            sudo systemctl restart ms-catalogo.service
            sleep 15
            sudo systemctl restart ms-recursos.service
            sleep 15
            sudo systemctl restart api-gateway.service